server:
  port: 8082

spring:
  application:
    name: ingestao

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    export:
      metrics:
        enabled: true
      prometheus:
        enabled: true
  health:
    db:
      enabled: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 4
        waitDuration: 500ms
        intervalFunction:
          type: exponential
          multiplier: 2
          randomizationFactor: 0.5
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.net.ConnectException
    instances:
      accountServiceRetry:
        baseConfig: default
      transactionServiceRetry:
        baseConfig: default

# Config AWS SDK / SQS (Localstack)
aws:
  region: sa-east-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  sqs:
    endpoint: ${SQS_ENDPOINT}
    queue-name: ${QUEUE_NAME}
    listener:
      concurrency: 10
      max-number-of-messages: 10
      wait-time-seconds: 30
