server:
  port: 8080

spring:
  application:
    name: consulta

  datasource:
    url: jdbc:postgresql://localhost:5433/contas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
    show-sql: false

#Actuator
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    export:
      metrics:
        enabled: true
      prometheus:
        enabled: true