server:
  port: 8080

spring:
  application:
    name: consulta

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
    show-sql: false

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    export:
      metrics:
        enabled: true
      prometheus:
        enabled: true
  health:
    db:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 4
        waitDuration: 500ms
        intervalFunction:
          type: exponential
          multiplier: 2
          randomizationFactor: 0.5
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.net.ConnectException
    instances:
      accountServiceRetry:
        baseConfig: default
        ignoreExceptions:
          - com.itau.consulta.exceptions.AccountNotFoundException
      transactionServiceRetry:
        baseConfig: default
        ignoreExceptions:
          - com.itau.consulta.exceptions.TransactionNotFoundException